In [461]:
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()

driver.get("https://www.traveloka.com/en-id/hotel/search?spec=25-05-2024.26-05-2024.1.1.HOTEL_GEO.102760.Kuta.1")

In [643]:
panjang = 45
awal = 20

In [675]:
dict_hotel = {}

for i in range(awal, panjang, 1):
    for j in range(1, 4, 1):
        try :
            xpath_hotel  = f"/html/body/div[1]/div[5]/div[2]/div/div[2]/div[5]/div/div[{i}]/div/div/div/div[2]/div[1]/div[1]/div[{j}]/h3"
            dict_hotel[i] = driver.find_elements(By.XPATH, xpath_hotel)[0].text
            print(i, dict_hotel[i])
        except:
            continue

20 Interconnection Hostel Kuta
21 New Pondok Sara Villas
22 Bali Sunset Villa Seminyak
23 ALA Hostel Seminyak
24 Guna Graha Kuta by Kamara
25 Bhavana Private Villa
26 Bali Chaya Hotel
27 Taman Amertha Villas

In [670]:
dict_harga = {}

for i in range(awal, panjang, 1): 
    try :
        xpath_harga = f"/html/body/div[1]/div[5]/div[2]/div/div[2]/div[5]/div/div[{i}]/div/div/div/div[3]/div/div/div[1]/div[3]/div/div[3]/div[1]"
        dict_harga[i] = driver.find_elements(By.XPATH, xpath_harga)[0].text
        print(i, dict_harga[i])
    except IndexError:
        continue

20 Rp 910.301
21 Rp 3.910.050
22 Rp 460.542
23 Rp 1.285.070
24 Rp 537.190
25 Rp 74.380
26 Rp 430.000
27 Rp 1.683.234
28 Rp 495.868
29 Rp 2.007.922
30 Rp 1.652.893
31 Rp 144.628
32 Rp 678.135
33 Rp 723.140
34 Rp 1.654.546
35 Rp 336.151
36 Rp 1.517.356
37 Rp 484.975
38 Rp 912.397
40 Rp 5.510.645
41 Rp 192.273
42 Rp 498.423
43 Rp 2.439.631

In [671]:
dict_reviews = {}

for i in range(awal, panjang, 1):
    for j in range(1, 4, 1):
        try :
            xpath_reviews = f"/html/body/div[1]/div[5]/div[2]/div/div[2]/div[5]/div/div[{i}]/div/div/div/div[2]/div[1]/div[1]/div[{j}]/div[1]/div[2]/span"
            dict_reviews[i] = driver.find_elements(By.XPATH, xpath_reviews)[0].text
            print(i, dict_reviews[i])
        except IndexError:
            continue

20 (219 reviews)
21 (37 reviews)
22 (70 reviews)
23 (48 reviews)
24 (58 reviews)
25 (85 reviews)
26 (10 reviews)
27 (6 reviews)
28 (212 reviews)
29 (20 reviews)
31 (104 reviews)
33 (27 reviews)
35 (44 reviews)
36 (38 reviews)
38 (67 reviews)
40 (29 reviews)
41 (39 reviews)
42 (27 reviews)
43 (118 reviews)

In [672]:
dict_rating = {}

for i in range(awal, panjang, 1):
    for j in range(1, 4, 1):
        try :
            xpath_rating = f"/html/body/div[1]/div[5]/div[2]/div/div[2]/div[5]/div/div[{i}]/div/div/div/div[2]/div[1]/div[1]/div[{j}]/div[1]/div[2]"
            dict_rating[i] = driver.find_elements(By.XPATH, xpath_rating)[0].text
            print(i, dict_rating[i])
        except IndexError:
            continue

20  8.2 (219 reviews)
21  8.7 (37 reviews)
22  8.8 (70 reviews)
23  8.6 (48 reviews)
24  8.3 (58 reviews)
25  8.3 (85 reviews)
26  9.1 (10 reviews)
27  8.8 (6 reviews)
28  8.5 (212 reviews)
29  9.0 (20 reviews)
31  8.4 (104 reviews)
33  8.9 (27 reviews)
35  8.1 (44 reviews)
36  9.1 (38 reviews)
38  8.9 (67 reviews)
39 Sun Royal Hotel
Hotels
 8.4
Kuta, Kuta
Save 10%!
Rp 483.471
Exclude taxes & fees
39 Atanaya Kuta Bali
Hotels
 8.6
Kuta, Kuta
Save 48%
Rp 515.200
Exclude taxes & fees
40  8.8 (29 reviews)
41  8.8 (39 reviews)
42  8.2 (27 reviews)
43  8.4 (118 reviews)

In [673]:
dict_facilities = {}

for i in range(awal, panjang, 1): 
    try :
        xpath_facilities = f"/html/body/div[1]/div[5]/div[2]/div/div[2]/div[5]/div/div[{i}]/div/div/div/div[2]/div[1]/div[2]/div[3]/div[2]"
        dict_facilities[i] = driver.find_elements(By.XPATH, xpath_facilities)[0].text
        print(i, f"{dict_facilities[i]}")
    except IndexError:
        continue

20 Pay at Hotel
Banana boat
Beach volleyball
Billiard
2+
21 Surfing
Horse riding
Massage
Kitchenette
Express check-out
1+
22 Car rental
23 Bar
Bicycle rental
Car rental
Massage
Bar
24 Bicycle rental
Car rental
Express check-out
26 Pay at Hotel
Express check-out
27 Massage
Kitchenette
Spa
28 Pay at Hotel
Bicycle rental
Car rental
Bar
29 Spa
30 Kitchenette
31 Pay at Hotel
33 Massage
Kitchenette
Pool sun loungers
35 Pay at Hotel
Bicycle storage
Bicycle rental
Beach towel
2+
37 Beach shuttle
Bicycle rental
Rooftop terrace
Airport transfer
2+
38 Pay at Hotel
Car rental
Poolside bar
Spa
40 Hot tub
Massage
Kitchenette
Express check-out
Picnic area
Spa
42 Pool sun loungers
Spa
43 Babysitting
Bicycle rental
Car rental
Massage
Fitness center
Spa

In [674]:
nama = []
harga = []
reviews = []
rating = []
facilities = []

# buatkan fungsi untuk menghitung panjang minimum dari dictionary, dan kembalikan dictionary
def min_length():
    return min(len(dict_hotel), len(dict_harga), len(dict_reviews), len(dict_rating), len(dict_facilities))

def dict_minimum():
    n = min_length()

    if(len(dict_hotel) == n):
        return dict_hotel
    elif(len(dict_harga) == n):
        return dict_harga
    elif(len(dict_reviews) == n):
        return dict_reviews
    elif(len(dict_rating) == n):
        return dict_rating
    else:
        return dict_facilities

dict_iterator = dict_minimum()

for i in dict_iterator.keys():
    try :
        nama.append(dict_hotel[i])
        harga.append(dict_harga[i])
        reviews.append(dict_reviews[i])
        rating.append(dict_rating[i])
        facilities.append(dict_facilities[i])
    except KeyError:
        continue
    
print(len(nama))
print(len(harga))
print(len(reviews))
print(len(rating))
print(len(facilities))

18
18
16
16
16

In [667]:
import pandas as pd

df = pd.DataFrame({'nama': nama, 'harga': harga, 'reviews': reviews, 'rating': rating, 'facilities': facilities})
df

,nama,harga,reviews,rating,facilities
0,Coast Boutique Hotel,Rp 810.114,(151 reviews),8.7 (151 reviews),Pay at Hotel\nAirport transfer
1,Away Bali Legian Camakila Resort,Rp 2.258.924,(54 reviews),8.5 (54 reviews),Kids club\nMassage\nFitness center\nWheelchair...
2,The Bandha Hotel & Suites,Rp 6.832.244,(68 reviews),8.9 (68 reviews),Hot tub\nBeach towel\nMassage\nFitness center\n2+
3,Destiny Villas and Residence,Rp 2.640.000,(45 reviews),8.6 (45 reviews),Babysitting\nBicycle rental\nCar rental\nMassa...
4,Ping Hotel,Rp 458.182,(244 reviews),8.4 (244 reviews),Pay at Hotel\nCar rental
5,Sri Krisna II,Rp 351.240,(67 reviews),8.5 (67 reviews),Pay at Hotel\nBraille or raised signage\nHot t...
6,Kelan-Tel Bali,Rp 304.132,(34 reviews),7.4 (34 reviews),Bicycle rental\nCar rental\nPool sun loungers\...
7,Sun Island Boutique Villas & Spa Seminyak,Rp 2.541.322,(11 reviews),8.5 (11 reviews),Pay at Hotel\nCar rental\nMassage\nKitchenette...
8,Amadea Resort & Villas Seminyak Bali,Rp 1.444.724,(79 reviews),8.7 (79 reviews),Massage\nSpa\nBar
9,Samaja Beachside Villas,Rp 1.924.429,(262 reviews),8.6 (262 reviews),Winery\nBicycle rental\nMassage\nKitchenette\n...
10,Pondok Sari Hotel,Rp 408.288,(472 reviews),8.5 (472 reviews),Pay at Hotel\nCar rental
11,Lavender Villa & Spa,Rp 770.668,(27 reviews),8.0 (27 reviews),Hot tub\nKaraoke\nChildren play area\nPool sun...
12,Villa de Malicott Athena,Rp 1.331.910,(25 reviews),8.1 (25 reviews),Express check-out
13,"The Legian, Bali",Rp 13.708.772,(13 reviews),8.9 (13 reviews),Health club\nAirport transfer\nBeach umbrella\...
14,Hotel Karthi,Rp 289.256,(693 reviews),8.4 (693 reviews),Massage
15,Bali Bungalo,Rp 590.909,(58 reviews),8.1 (58 reviews),Bicycle storage\nClothes dryer\nBicycle rental...
16,Cattleya Pool Suite - Seminyak by Marbella,Rp 910.301,(219 reviews),8.2 (219 reviews),Pay at Hotel\nBanana boat\nBeach volleyball\nB...
17,The Akasha Luxury Villas,Rp 3.910.050,(37 reviews),8.7 (37 reviews),Surfing\nHorse riding\nMassage\nKitchenette\nE...
18,Interconnection Hostel Kuta,Rp 460.542,(70 reviews),8.8 (70 reviews),Car rental

In [668]:
df.to_csv("part15.csv", index=False)